DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS restaurant;

CREATE TABLE restaurant
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                             NOT NULL,
    address VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);

ALTER TABLE restaurant
    ADD CONSTRAINT uc_restaurant_name UNIQUE (name);

CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                             NOT NULL,
    password      VARCHAR(255)                             NOT NULL,
    email         VARCHAR(255)                             NOT NULL,
    restaurant_id INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE TABLE item
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255)                             NOT NULL,
    description   VARCHAR(255)                             NOT NULL,
    restaurant_id INTEGER,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE;